#pragma once
#include <iostream>
#include <cmath>
#include <vector>
#include <stdio.h>
#include <stdlib.h>
#include <chrono>
#include <string.h>
#include <string>
using std::string;
#include <iostream>
using std::cout;