#pragma once
#include <iostream>
#include <cmath>
#include <vector>
#include <stdio.h>
#include <stdlib.h>
#include <chrono>
#include <string.h>
#include <string>
#include <fstream>
using std::ifstream;
using std::getline;
using std::ios;
using std::string;
#include <list>
#include <iostream>
using std::cout;
#include <fstream>
#include <algorithm>
#include <glad/glad.h>
#include <GLFW/glfw3.h>
#include "utils.h"

